COUNTRY_NAMES_PT = {
    "AF": "Afeganistão", "AL": "Albânia", "DZ": "Argélia", "AD": "Andorra",
    "AO": "Angola", "AG": "Antígua e Barbuda", "AR": "Argentina", "AM": "Armênia",
    "AU": "Austrália", "AT": "Áustria", "AZ": "Azerbaijão", "BS": "Bahamas",
    "BH": "Bahrein", "BD": "Bangladesh", "BB": "Barbados", "BY": "Bielorrússia",
    "BE": "Bélgica", "BZ": "Belize", "BJ": "Benin", "BT": "Butão",
    "BO": "Bolívia", "BA": "Bósnia e Herzegovina", "BW": "Botsuana", "BR": "Brasil",
    "BN": "Brunei", "BG": "Bulgária", "BF": "Burkina Faso", "BI": "Burundi",
    "KH": "Camboja", "CM": "Camarões", "CA": "Canadá", "CV": "Cabo Verde",
    "CF": "República Centro-Africana", "TD": "Chade", "CL": "Chile", "CN": "China",
    "CO": "Colômbia", "KM": "Comores", "CG": "Congo", "CD": "Rep. Dem. do Congo",
    "CR": "Costa Rica", "CI": "Costa do Marfim", "HR": "Croácia", "CU": "Cuba",
    "CY": "Chipre", "CZ": "República Tcheca", "DK": "Dinamarca", "DJ": "Djibuti",
    "DM": "Dominica", "DO": "República Dominicana", "EC": "Equador", "EG": "Egito",
    "SV": "El Salvador", "GQ": "Guiné Equatorial", "ER": "Eritreia", "EE": "Estônia",
    "ET": "Etiópia", "FJ": "Fiji", "FI": "Finlândia", "FR": "França",
    "GA": "Gabão", "GM": "Gâmbia", "GE": "Geórgia", "DE": "Alemanha",
    "GH": "Gana", "GR": "Grécia", "GD": "Granada", "GT": "Guatemala",
    "GN": "Guiné", "GW": "Guiné-Bissau", "GY": "Guiana", "HT": "Haiti",
    "HN": "Honduras", "HK": "Hong Kong", "HU": "Hungria", "IS": "Islândia",
    "IN": "Índia", "ID": "Indonésia", "IR": "Irã", "IQ": "Iraque",
    "IE": "Irlanda", "IL": "Israel", "IT": "Itália", "JM": "Jamaica",
    "JP": "Japão", "JO": "Jordânia", "KZ": "Cazaquistão", "KE": "Quênia",
    "KI": "Kiribati", "KP": "Coreia do Norte", "KR": "Coreia do Sul", "KW": "Kuwait",
    "KG": "Quirguistão", "LA": "Laos", "LV": "Letônia", "LB": "Líbano",
    "LS": "Lesoto", "LR": "Libéria", "LY": "Líbia", "LI": "Liechtenstein",
    "LT": "Lituânia", "LU": "Luxemburgo", "MK": "Macedônia do Norte", "MG": "Madagascar",
    "MW": "Malawi", "MY": "Malásia", "MV": "Maldivas", "ML": "Mali",
    "MT": "Malta", "MH": "Ilhas Marshall", "MR": "Mauritânia", "MU": "Maurício",
    "MX": "México", "FM": "Micronésia", "MD": "Moldávia", "MC": "Mônaco",
    "MN": "Mongólia", "ME": "Montenegro", "MA": "Marrocos", "MZ": "Moçambique",
    "MM": "Mianmar", "NA": "Namíbia", "NR": "Nauru", "NP": "Nepal",
    "NL": "Países Baixos", "NZ": "Nova Zelândia", "NI": "Nicarágua", "NE": "Níger",
    "NG": "Nigéria", "NO": "Noruega", "OM": "Omã", "PK": "Paquistão",
    "PW": "Palau", "PA": "Panamá", "PG": "Papua-Nova Guiné", "PY": "Paraguai",
    "PE": "Peru", "PH": "Filipinas", "PL": "Polônia", "PT": "Portugal",
    "QA": "Catar", "RO": "Romênia", "RU": "Rússia", "RW": "Ruanda",
    "KN": "São Cristóvão e Neves", "LC": "Santa Lúcia", "VC": "São Vicente e Granadinas",
    "WS": "Samoa", "SM": "San Marino", "ST": "São Tomé e Príncipe", "SA": "Arábia Saudita",
    "SN": "Senegal", "RS": "Sérvia", "SC": "Seicheles", "SL": "Serra Leoa",
    "SG": "Singapura", "SK": "Eslováquia", "SI": "Eslovênia", "SB": "Ilhas Salomão",
    "SO": "Somália", "ZA": "África do Sul", "ES": "Espanha", "LK": "Sri Lanka",
    "SD": "Sudão", "SR": "Suriname", "SZ": "Eswatini", "SE": "Suécia",
    "CH": "Suíça", "SY": "Síria", "TW": "Taiwan", "TJ": "Tajiquistão",
    "TZ": "Tanzânia", "TH": "Tailândia", "TL": "Timor-Leste", "TG": "Togo",
    "TO": "Tonga", "TT": "Trinidad e Tobago", "TN": "Tunísia", "TR": "Turquia",
    "TM": "Turcomenistão", "TV": "Tuvalu", "UG": "Uganda", "UA": "Ucrânia",
    "AE": "Emirados Árabes Unidos", "GB": "Reino Unido", "US": "Estados Unidos",
    "UY": "Uruguai", "UZ": "Uzbequistão", "VU": "Vanuatu", "VA": "Vaticano",
    "VE": "Venezuela", "VN": "Vietnã", "YE": "Iêmen", "ZM": "Zâmbia", "ZW": "Zimbábue",
    "PS": "Palestina", "XK": "Kosovo", "SS": "Sudão do Sul", "CW": "Curaçao",
    "SX": "São Martinho", "PR": "Porto Rico", "GU": "Guam", "VI": "Ilhas Virgens (EUA)",
}

COUNTRY_NAMES_EN = {
    "AF": "Afghanistan", "AL": "Albania", "DZ": "Algeria", "AD": "Andorra",
    "AO": "Angola", "AR": "Argentina", "AM": "Armenia", "AU": "Australia",
    "AT": "Austria", "AZ": "Azerbaijan", "BS": "Bahamas", "BH": "Bahrain",
    "BD": "Bangladesh", "BB": "Barbados", "BY": "Belarus", "BE": "Belgium",
    "BR": "Brazil", "BG": "Bulgaria", "CA": "Canada", "CL": "Chile",
    "CN": "China", "CO": "Colombia", "CR": "Costa Rica", "HR": "Croatia",
    "CU": "Cuba", "CY": "Cyprus", "CZ": "Czech Republic", "DK": "Denmark",
    "DO": "Dominican Republic", "EC": "Ecuador", "EG": "Egypt", "EE": "Estonia",
    "FI": "Finland", "FR": "France", "DE": "Germany", "GH": "Ghana",
    "GR": "Greece", "GT": "Guatemala", "HK": "Hong Kong", "HU": "Hungary",
    "IS": "Iceland", "IN": "India", "ID": "Indonesia", "IR": "Iran",
    "IQ": "Iraq", "IE": "Ireland", "IL": "Israel", "IT": "Italy",
    "JM": "Jamaica", "JP": "Japan", "JO": "Jordan", "KZ": "Kazakhstan",
    "KE": "Kenya", "KR": "South Korea", "KW": "Kuwait", "LV": "Latvia",
    "LB": "Lebanon", "LT": "Lithuania", "LU": "Luxembourg", "MY": "Malaysia",
    "MX": "Mexico", "MA": "Morocco", "NL": "Netherlands", "NZ": "New Zealand",
    "NG": "Nigeria", "NO": "Norway", "PK": "Pakistan", "PA": "Panama",
    "PY": "Paraguay", "PE": "Peru", "PH": "Philippines", "PL": "Poland",
    "PT": "Portugal", "QA": "Qatar", "RO": "Romania", "RU": "Russia",
    "SA": "Saudi Arabia", "RS": "Serbia", "SG": "Singapore", "SK": "Slovakia",
    "SI": "Slovenia", "ZA": "South Africa", "ES": "Spain", "LK": "Sri Lanka",
    "SE": "Sweden", "CH": "Switzerland", "TW": "Taiwan", "TH": "Thailand",
    "TR": "Turkey", "UA": "Ukraine", "AE": "United Arab Emirates",
    "GB": "United Kingdom", "US": "United States", "UY": "Uruguay",
    "VE": "Venezuela", "VN": "Vietnam",
}

COUNTRY_NAMES_LOCAL = {
    "pt": COUNTRY_NAMES_PT,
    "en": COUNTRY_NAMES_EN
}